### ISSUE TITLE
Update Sparkle version for security reasons

### ISSUE THREAD

**Issue by christopheranderton** [insidegui/VLCX#1]
While i understand this may not be a priority. The version of the Sparkle framework uses http instead of https, leaving Sparkle vulnerable to man in the middle attacks. It has been updated, but there are reports of that it's not that easy to update. 

More info: http://www.mackungfu.org/how-to-find-if-your-apps-are-affected-by-the-sparkle-hijack

**Comment by insidegui** [comment]
I am aware of this and will update as soon as I can.

**Comment by insidegui** [comment]
v1.0.3 fixes this by using HTTPs. I migrated my DNS to CloudFlare to get their free SSL so It may take a while for the update to work.
